### ISSUE TITLE
게임시작 화면

### ISSUE THREAD

**Issue by hil00137** [pomeryt/Alchemist#1]
title

밑에 버튼 4개
start
load
option
exit

**Comment by pomeryt** [comment]
Finish, please check.

**Comment by HeeraKim** [comment]
이 게임에 대해서 써주세요. @hil00137

**Comment by pomeryt** [comment]
게임에 대한 전체적 설명은 Wiki에 있는 Home페이지에 써주셍.
@hil00137 @HeeraKim

**Comment by pomeryt** [comment]
게임 시작화면의 컨셉아트를 여기에 첨부바람.
@HeeraKim

**Comment by hil00137** [comment]
wiki home에 간단히 써봤어요 @HeeraKim
