### ISSUE TITLE
Log

### ISSUE THREAD

**Issue by pomeryt** [pomeryt/Alchemist#13]
## Motivation

During the development, we want to print something to check if the code works correctly.
Creating a log helps us diagnose the code.

## Requirements

- The log file should be created in the specified path.
- Files should be organized based on hour.
- Each print statements should include the following: 
date, time, class name, method name, message, and stacktrace in case of exception.

## What should file name look like?

The file name has following format:
Title_Year_Month_Day_Hour.extension
Use 24-hour clock.
Ex) Alchemist_2018_08_05_15.log

The extension of file would be determined by Revomin.

## How print statement look like?

Sample output:
> [1:47:13] [application.Main] [start()] Test log.

**Comment by hil00137** [comment]
@pomeryt Log System, I've done. check please
